### ISSUE TITLE
Issue in training the 'tutorial-2-image-classifier'

### ISSUE THREAD

**Issue by ashukl** [legolas123/cv-tricks.com#14]
Hi Ankit,

I am new to image classification. I cloned your repository and tried to run the code train.py in my system. I just keep getting an error message saying: 
"2018-06-17 00:19:55.817737: W tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at save_restore_v2_ops.cc:109 : Not found: ; No such file or directory
Traceback (most recent call last):
  File "train.py", line 206, in <module>
    train(num_iteration=3000)
  File "train.py", line 201, in train
    saver.save(session, 'dogs-cats-model') 
  File "/Users/z001txn/anaconda/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1720, in save
    raise exc
ValueError: Parent directory of dogs-cats-model doesn't exist, can't save."

I think the problem is in saving the model but I am not able to figure out how to solve it. Can you please help me out here.

Thanks,
Aishwarya

**Comment by andres020202** [comment]
Hi! i just had the same problem. You need to use a path instead of just a name to be able to save the model. So instead of 'dogs-cats-model' you can use './dogs-cats-model'. Here is where I found the solution: https://stackoverflow.com/questions/42134360/tensorflow-valueerror-parent-directory-of-trained-variables-ckpt-doesnt-exis.

**Comment by ashukl** [comment]
Thanks a lot, it worked for me :)
